# https://golangci-lint.run
run:
  timeout: 5m
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - deepequalerrors
    - depguard
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - importas
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
    - zerologlint

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/sentinel-cnapp
  gocyclo:
    min-complexity: 15
  gocognit:
    min-complexity: 20
  misspell:
    locale: US
  lll:
    line-length: 140
  dupl:
    threshold: 100
  nestif:
    min-complexity: 5
  revive:
    rules:
      - name: exported
        severity: warning
      - name: package-comments
        disabled: true

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - errcheck
        - gochecknoglobals
        - gosec
        - wrapcheck
        - dupl
    - path: pkg/finding
      linters:
        - gochecknoglobals
