apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sentinel-cnapp.fullname" . }}-webhook
type: Opaque
stringData:
  secret: "{{ .Values.global.webhookSecret | default "changeme-webhook-secret" }}"
